### ISSUE TITLE
有\n的问题解决了吗??我用到项目里了  报错

### ISSUE THREAD

**Issue by baoyu1990** [Carbs0126/ExpandableTextView#7]

**Comment by baoyu1990** [comment]
有\n这里报错
int remainWidth = getValidLayout().getWidth() -
                        (int) (mTextPaint.measureText(mOrigText.subSequence(indexStart, indexEndTrimmed).toString()) + 0.5);
                float widthTailReplaced = mTextPaint.measureText(getContentOfString(mEllipsisHint)
                        + (mShowToExpandHint ? (getContentOfString(mToExpandHint) + getContentOfString(mGapToExpandHint)) : ""));

**Comment by Carbs0126** [comment]
这个问题更新了，你可以更改一下依赖：
compile 'cn.carbs.android:ExpandableTextView:1.0.3'
